<?php
/**
 * Add metaboxes for an episode page.
 * @package FanKit
 */

// TODO: episode parser
// "the episode parser adds characters to episodes automatically,"
// "but if you'd like to manually mark the character as being in an episode"
// "simply check the box"
// - have episodes arranged by season
// - TODO:JS do accordion dealie with jQuery so we don't show like 7 seasons at once
//   - one season at a time
// - "You may want to drag the name box up or on the side so you don't
//    have to scroll down"
// 2 things, 2 boxes

/**
 * Add all metaboxes for an episode page.
 * @todo mark characters that are in this episode (checkboxes)
 */
function fk_add_episode_boxes(){
	add_action('admin_menu', '_fk_episode_boxes');
}

/**
 * Show a little how-to intro message for episodes. Hooked by fk-boxes.php.
 */
function fk_episode_notices(){
	global $post;
	$new_ep_txt = '';
	if( 0 === $post->ID ){
		$new_ep_txt = __('You are adding a new episode.') . ' ';
	}
	$txt = $new_ep_txt . __("The page title will be the episode title, and the page content will be the episode description. To add more information, including a transcript, use the boxes below the writing area. To add an autogenerated quote page, do BLAHHH"); // FIXME
	fk_show_basic_notice($txt);
}

function _fk_episode_boxes(){
	if( function_exists('add_meta_box')){
		// Add a box where user specifies the general episode info.
		add_meta_box('fk_episode_box_id', __("TV Fan Kit - Episode Information"), 'fk_episode_info_box_cb', 'page', 'normal');
		// Add separate box for transcript, since it can be huge and user may want to drag it out of the way.
		add_meta_box('fk_episode_box_transcript_id', __("TV Fan Kit - Episode Transcript"), 'fk_episode_transcript_box_cb', 'page', 'normal');
	}
}

// Callback for general episode info metabox
function fk_episode_info_box_cb(){
	global $post, $fk_settings;
	list($default_season, $default_ep_num) = fk_episode_get_season_ep_num($post->ID);
	if( $default_season === false || $default_ep_num === false ){
		$default_season = '';
		$default_ep_num = '';
	}

	// Note that we may have episodes w/o season or ep_num, eg a page
	// that was switched to episode from another type.
	wp_nonce_field('fk_set_episode_info', 'fk_episode_info_nonce');
	echo '<div class="form-wrap">';
	printf('<label for="fk_season_id">%s:</label>', __('Season'));
	echo '<input type="text" id="fk_season_id" name="fk_season" value="'.$default_season.'" size="10" tabindex="200" />';
	printf('<label for="fk_ep_num_id">%s:</label>', __('Episode Number'));
	echo '<input type="text" id="fk_ep_num_id" name="fk_ep_num" value="'.$default_ep_num.'" size="10" tabindex="201" />';
	echo '</div>';
	
	echo '<p>';
	if( 0 === $post->ID ){
		_e("After you've saved this page you can mark characters who appeared in this episode.");
	} else {
		$characters = fk_episode_get_appearances($post->ID);
		$all_characters = fk_character_get_all(); // sorted by first name
		if( empty($characters) ){
			_e("<p>No characters have been marked as appearing in this episode.</p>");
		}
		if( empty($all_characters) ){
			printf(__('<p>No characters have been added. Maybe you want to <a href="%s">add one</a>?</p>'),
				$fk_settings->new_character_link);
		} else {
			echo '<p>';
			foreach( (array) $all_characters as $ch ){
				// FIXME - characters by letter
				$current_letter = '';
				$checked = fk_character_appears_in($ch->character_id, $post->ID) ? ' checked="checked"' : '';
				printf('<label><input type="checkbox" name="appearances[]" value="%1$s" %2$s /> %3$s</label>',
				       $ch->character_id, $checked, $ch->name);
				echo '<br />';
			}
			echo '</p>';
		}

		//dpr($characters);
		//dpr($all_characters);
	}
	echo '</p>';
}

// Callback for transcript metabox
function fk_episode_transcript_box_cb(){
	wp_nonce_field('fk_set_episode_transcript', 'fk_episode_transcript_nonce');
}

function fk_save_page_episode($post_id){
	if( $_POST['action'] === 'inline-save' ){
		// TODO: episodes actually do parse post content, so somehow check if transcript has changed, and if it has
		// do stuff - wp supplies the nonce
		// - maybe use revisions, if they're enabled. Because they can be turned off - see page on editing wp-config.php
		return;
	}
	check_admin_referer('fk_set_episode_info', 'fk_episode_info_nonce');
	check_admin_referer('fk_set_episode_transcript', 'fk_episode_transcript_nonce');
	
	$season = $_POST['fk_season'];
	$ep_num = $_POST['fk_ep_num'];
	$appearances = $_POST['fk_appearances']; // TODO
	if( preg_match('/[^0-9]/', $season . $ep_num) ){
		// User entered non-numeric string for one of the vars. Break.
		return $post_id;
	}
	if( is_null($appearances) ){
		$appearances = array();
	}

	if( fk_episode_exists($post_id) ){
		$new = array('season' => $season,
			'ep_num' => $ep_num,
			'appearances' => $appearances);
		fk_episode_add($post_id, $season, $ep_num, $appearances);
	} else {
		fk_episode_add($post_id, $season, $ep_num, $appearances);
	}
}
?>
